//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLessonAutomationProjectCSharp.src.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterLessonAutomationProjectCSharp.src.TestData.HomePageTestData", typeof(HomePageTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your booking has been confirmed for:.
        /// </summary>
        internal static string BookingSuccessDescription {
            get {
                return ResourceManager.GetString("BookingSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Successful!.
        /// </summary>
        internal static string BookingSuccessHeader {
            get {
                return ResourceManager.GetString("BookingSuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old Farmhouse, Shady Street, Newfordburyshire, NE1 410S.
        /// </summary>
        internal static string ContactFormInnAddress {
            get {
                return ResourceManager.GetString("ContactFormInnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fake@fakeemail.com.
        /// </summary>
        internal static string ContactFormInnEmail {
            get {
                return ResourceManager.GetString("ContactFormInnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shady Meadows B&amp;B.
        /// </summary>
        internal static string ContactFormInnName {
            get {
                return ResourceManager.GetString("ContactFormInnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012345678901.
        /// </summary>
        internal static string ContactFormInnPhone {
            get {
                return ResourceManager.GetString("ContactFormInnPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll get back to you about.
        /// </summary>
        internal static string ContactFormSubmissionSuccessDescription {
            get {
                return ResourceManager.GetString("ContactFormSubmissionSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for getting in touch testfirst testlast!.
        /// </summary>
        internal static string ContactFormSubmissionSuccessHeader {
            get {
                return ResourceManager.GetString("ContactFormSubmissionSuccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testsubject.
        /// </summary>
        internal static string ContactFormSubmissionSuccessSubject {
            get {
                return ResourceManager.GetString("ContactFormSubmissionSuccessSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as soon as possible..
        /// </summary>
        internal static string ContactFormSubmissionSuccessTimeline {
            get {
                return ResourceManager.GetString("ContactFormSubmissionSuccessTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Shady Meadows, a delightful Bed &amp; Breakfast nestled in the hills on Newingtonfordburyshire. A place so beautiful you will never want to leave. All our rooms have comfortable beds and we provide breakfast from the locally sourced supermarket. It is a delightful place..
        /// </summary>
        internal static string InnDescriptionParagraph {
            get {
                return ResourceManager.GetString("InnDescriptionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string InnHeader {
            get {
                return ResourceManager.GetString("InnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aenean porttitor mauris sit amet lacinia molestie. In posuere accumsan aliquet. Maecenas sit amet nisl massa. Interdum et malesuada fames ac ante..
        /// </summary>
        internal static string RoomDescriptionParagraph {
            get {
                return ResourceManager.GetString("RoomDescriptionParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        internal static string RoomFeaturesListItemSafe {
            get {
                return ResourceManager.GetString("RoomFeaturesListItemSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string RoomFeaturesListItemTV {
            get {
                return ResourceManager.GetString("RoomFeaturesListItemTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi.
        /// </summary>
        internal static string RoomFeaturesListItemWiFi {
            get {
                return ResourceManager.GetString("RoomFeaturesListItemWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single.
        /// </summary>
        internal static string RoomHeader {
            get {
                return ResourceManager.GetString("RoomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.mwtestconsultancy.co.uk/img/testim/room2.jpg.
        /// </summary>
        internal static string RoomPictureSrc {
            get {
                return ResourceManager.GetString("RoomPictureSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testemail@test.com.
        /// </summary>
        internal static string TestEmail {
            get {
                return ResourceManager.GetString("TestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testfirst.
        /// </summary>
        internal static string TestFirstName {
            get {
                return ResourceManager.GetString("TestFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testfirst testlast.
        /// </summary>
        internal static string TestFullName {
            get {
                return ResourceManager.GetString("TestFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testlast.
        /// </summary>
        internal static string TestLastName {
            get {
                return ResourceManager.GetString("TestLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
        /// </summary>
        internal static string TestMessage {
            get {
                return ResourceManager.GetString("TestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-234-567-8901.
        /// </summary>
        internal static string TestPhone {
            get {
                return ResourceManager.GetString("TestPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testsubject.
        /// </summary>
        internal static string TestSubject {
            get {
                return ResourceManager.GetString("TestSubject", resourceCulture);
            }
        }
    }
}
